language: ruby
before_install: gem update bundler
install: bundle install --jobs 3 --retry 3 --without mutant
script: rake ci
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0'
    - rvm: jruby-head
      env: JRUBY_OPTS='--2.0'
  allow_failures:
    - rvm: jruby
    - rvm: jruby-head
    - rvm: mruby-head
    - rvm: rbx
addons:
  code_climate:
    repo_token: ebb97d3c606e22753911d08f39444a86f27a7da6a40d834f94d640375615fff8
